"""empty message

Revision ID: 99832168b2db
Revises: c84429424ca2
Create Date: 2024-06-06 19:45:18.197918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99832168b2db'
down_revision = 'c84429424ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
