"""empty message

Revision ID: c100f0c2fec3
Revises: 99832168b2db
Create Date: 2024-06-23 20:37:02.312425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c100f0c2fec3'
down_revision = '99832168b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('number_user', sa.Integer(), nullable=False),
    sa.Column('email_user', sa.String(), nullable=False),
    sa.Column('city_user', sa.String(), nullable=False),
    sa.Column('nova_poshta', sa.String(), nullable=False),
    sa.Column('additional_wishes', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('products', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
