"""empty message

Revision ID: ebe6c600acbc
Revises: 8cf8c48b019e
Create Date: 2024-05-25 20:15:04.491847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe6c600acbc'
down_revision = '8cf8c48b019e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('picture', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('picture')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
